import dotenv from 'dotenv';
dotenv.config();

export default {
  port: parseInt(process.env.PORT || '3000', 10),
  mongoUri: process.env.MONGO_URI || 'mongodb://localhost:27017/auth_service',
  cookieSecret: process.env.COOKIE_SECRET ?? 'cookie_secret_key',
  cookieDomain: process.env.COOKIE_DOMAIN ?? 'localhost',
  sessionSecret: process.env.SESSION_SECRET ?? 'session_secret_key',
  jwtSecret: process.env.JWT_SECRET ?? 'jwt_secret_key',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? 'jwt_refresh_secret_key',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '1h',
  jwtRefreshTokenExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN ?? '7d',
  clientUrl: process.env.CLIENT_URL ?? 'http://localhost:4200',
  nodeEnv: process.env.NODE_ENV || 'development',
  trustedProxies: process.env.TRUSTED_PROXIES?.split(',') || [],
  workerConcurrency: parseInt(process.env.WORKER_CONCURRENCY || '4', 10),
  redisHost: process.env.REDIS_HOST || 'localhost',
  redisPort: parseInt(process.env.REDIS_PORT || '6379', 10),
  redisPassword: process.env.REDIS_PASSWORD || undefined,
  s3Url: process.env.S3_ENDPOINT || '',
  s3PublicBucket: process.env.S3_BUCKET_PUBLIC || '',
  s3PrivateBucket: process.env.S3_BUCKET_PRIVATE || '',
  s3HlsBucket: process.env.S3_BUCKET_HLS || '',
  s3QuarantineBucket: process.env.S3_BUCKET_QUARANTINE || '',
  s3TempBucket: process.env.S3_BUCKET_TEMP || '',
  s3AccessKey: process.env.S3_APP_ACCESS || '',
  s3SecretKey: process.env.S3_APP_SECRET || '',
  s3QuarantineAccessKey: process.env.S3_QUARANTINE_ACCESS || '',
  s3QuarantineSecretKey: process.env.S3_QUARANTINE_SECRET || '',
};
